[package]
name = "asyncweb"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
mini-redis = "0.4"
#async-trait = "0.1"
hyper-reverse-proxy = "0.5"
hyper = { version = "0.14", features = ["full"] }
rand = "0.8.5"
dashmap = "6.1.0"
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
#pingora = { version = "0.4", features = ["full"] }
pingora = { version = "0.4.0", features = ["lb"] }
pingora-core = { version = "0.4.0" }
pingora-proxy = { version = "0.4.0" }
pingora-load-balancing = { version = "0.4.0" }
pingora-http = { version = "0.4.0" }
async-trait = { version = "0.1.85" }
env_logger = { version = "0.11.6" }
log = "0.4.25"
futures = "0.3.31"
notify = "8.0.0"

