[package]
name = "asyncweb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
pingora = { version = "0.4.0", features = ["lb", "openssl"] } # openssl, rustls, boringssl
serde = { version = "1.0.219", features = ["derive"] }
dashmap = "6.1.0"
pingora-core = "0.4.0"
pingora-proxy = "0.4.0"
pingora-http = "0.4.0"
async-trait = "0.1.88"
env_logger = "0.11.7"
log = "0.4.26"
futures = "0.3.31"
notify = "8.0.0"
axum = "0.8.1"
reqwest = "0.12.15"
serde_yaml = "0.8.26"